; DropIt installer — Inno Setup 6 script.
; Built on the Windows PC via build.bat (PyInstaller runs first, then ISCC).
; version.iss is generated by build.bat from dropit.py's VERSION — do not edit by hand.

#include "version.iss"

#define MyAppName "DropIt"
#define MyAppPublisher "Essef"

[Setup]
AppId={{AC6E5E09-DC00-426C-B293-CED68DFC4D20}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\DropIt
DefaultGroupName=DropIt
DisableProgramGroupPage=yes
OutputDir=dist-installer
; Stable file name on purpose: every release uploads its installer under this
; exact name, so the stub can always fetch the newest one from the
; .../releases/latest/download/DropIt-Setup.exe URL.
OutputBaseFilename=DropIt-Setup
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=lowest
; Refresh the shell so Start Menu icons appear immediately
AlwaysUsePersonalGroup=yes
CloseApplications=yes
RestartApplications=no
UninstallDisplayName=DropIt
VersionInfoVersion={#MyAppVersion}
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
Source: "dist\DropIt.exe"; DestDir: "{app}"; Flags: ignoreversion

[InstallDelete]
; Clean up leftovers from the old manual-install days (stray exe copies and
; the old Startup shortcut that kept launching ancient builds).
Type: files; Name: "{userdesktop}\DropIt.exe"
Type: files; Name: "{userstartup}\DropIt.lnk"
; Old per-user installs lived here before the installer standardized the path
Type: filesandordirs; Name: "{localappdata}\DropIt"

[Icons]
Name: "{group}\DropIt"; Filename: "{app}\DropIt.exe"
Name: "{group}\Uninstall DropIt"; Filename: "{uninstallexe}"
Name: "{userdesktop}\DropIt"; Filename: "{app}\DropIt.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\DropIt.exe"; Description: "Launch DropIt now"; Flags: nowait postinstall skipifsilent

[Code]
// Kill any running DropIt before installing so DropIt.exe isn't file-locked.
procedure KillRunningDropIt();
var
  ResultCode: Integer;
begin
  Exec('taskkill.exe', '/F /IM DropIt.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

function InitializeSetup(): Boolean;
begin
  KillRunningDropIt();
  Result := True;
end;

// The app's own "Start with Windows" toggle points at its own exe path.
// Since the installer always uses the same folder, that registry entry keeps
// working across updates — no repair needed after an upgrade.
